export default [
  {
    name: "Datenlöschen",
    slug: "datenloschen",
    path: "",
    question:
      "<p>Du kannst gem. Art. 15 DSGVO erfragen, welche Daten ein Unternehmen von dir hat. Ich bin dir gerne bei der Anfrage behilflich.</p>\n\n<p>Wie hei&szlig;t das Unternehmen, bei dem du deine Anfrage stellen willst?</p>",
    inputs: [
      {
        input_type: "free_text",
        text: "Unternehmensname",
        validation: "short_text",
        destination: "6",
      },
    ],
    newNode: false,
    startNode: false,
    endNode: false,
    extraData: "",
    id: "1",
    createdAt: "2020-06-12T12:29:30.748963+00:00",
  },
  {
    name: "Einstieg",
    slug: "einstieg",
    path: "",
    question: "<p>Was willst du tun?</p>",
    inputs: [
      {
        input_type: "button",
        text: "Auskunft über Daten bei einem Unternehmen",
        destination: "4",
      },
      {
        input_type: "button",
        text: "Einwilligungswiderruf",
        destination: "8",
      },
      {
        input_type: "button",
        text: "Datenlöschungsanfrage",
        destination: "1",
      },
      {
        input_type: "button",
        text: "Werbewiderruf",
        destination: "7",
      },
    ],
    newNode: false,
    startNode: true,
    endNode: false,
    extraData: "",
    id: "2",
    createdAt: "2020-06-12T12:29:30.759739+00:00",
  },
  {
    name: "awda",
    slug: "awda",
    path: null,
    question: "<p>awd</p>",
    inputs: [
      {
        input_type: "button",
        text: "",
        destination: "",
      },
    ],
    newNode: false,
    startNode: false,
    endNode: false,
    extraData: null,
    id: "3",
    createdAt: "2020-06-29T12:46:49.910541+00:00",
  },
  {
    name: "Datenauskunft",
    slug: "datenauskunft",
    path: null,
    question: "",
    inputs: [{}],
    newNode: true,
    startNode: false,
    endNode: false,
    extraData: null,
    id: "4",
    createdAt: "2020-06-17T16:16:11.309864+00:00",
  },
  {
    name: "Schreiben Löschung",
    slug: "schreiben-loschung",
    path: null,
    question:
      "<p>Guten Tag,</p>\n\n<p>ich stelle hiermit Antrag auf unverz&uuml;gliche L&ouml;schung mich betreffender personenbezogener Daten gem&auml;&szlig; Art. 17 Abs. 1 DSGVO.</p>\n\n<p>Meine Kundennr. lautet&nbsp;[[kundendaten-loschung.kundenummer]]</p>\n\n<p>Bitte l&ouml;schen Sie s&auml;mtliche mich betreffenden personenbezogenen Daten nach der Definition des Art. 4 Nr. 1 DSGVO.</p>\n\n<p>Ich bin der Meinung, dass die Voraussetzungen des Art. 17 Abs. 1 DSGVO gegeben sind. Sie k&ouml;nnen auch keinen Ausnahmetatbestand nach Art. 17 Abs. 3 DSGVO geltend machen, zumal ich keine Person des &ouml;ffentlichen Lebens bin.</p>\n\n<p>Sollte ich eine Einwilligung zur Verarbeitung meiner Daten (bspw. nach Art. 6 Abs. 1 lit. a oder Art. 9 Abs. 2 DSGVO) erteilt haben, widerrufe ich diese hiermit f&uuml;r den gesamten Prozess der Datenverarbeitung.<br>\nWeiterhin lege ich im Sinne des Art. 21 DSGVO Widerspruch gegen die Verarbeitung mich betreffender personenbezogener Daten ein, dies gilt auch f&uuml;r Profiling. Ich fordere Sie auf, die Verarbeitung der mich betreffenden Daten gem&auml;&szlig; Art. 18 Abs. 1 lit. d DSGVO einzuschr&auml;nken, solange noch nicht feststeht, ob Ihre berechtigten Gr&uuml;nde gegen&uuml;ber meinen &uuml;berwiegen.</p>\n\n<p>Falls Sie die betroffenen Daten &ouml;ffentlich gemacht haben sollten, sind Sie nach Art. 17 Abs. 2 DSGVO dazu verpflichtet, alle angemessenen Ma&szlig;nahmen zu treffen, um andere Verantwortliche, beispielsweise Suchmaschinenbetreiber, welche die oben aufgef&uuml;hrten personenbezogenen Daten verarbeiten, &uuml;ber meinen Antrag auf L&ouml;schung aller Links, Kopien oder Replikationen zu informieren. Dies gilt nicht nur f&uuml;r exakte Kopien der betroffenen Daten, sondern auch f&uuml;r solche, aus denen in den betroffenen Daten enthaltene Informationen entnehmbar sind.</p>\n\n<p>Sofern Sie die betroffenen personenbezogenen Daten einem oder mehreren Empf&auml;ngern im Sinne des Art. 4 Nr. 9 DSGVO offengelegt haben, haben Sie meinen Wunsch auf L&ouml;schung der genannten personenbezogenen Daten und s&auml;mtlicher Verweise darauf nach Art. 19 DSGVO auch allen solchen Empf&auml;ngern mitzuteilen. Bitte informieren Sie mich weiterhin &uuml;ber diese Empf&auml;nger.</p>\n\n<p>Sollten Sie die L&ouml;schung ablehnen, haben Sie dies mir gegen&uuml;ber zu begr&uuml;nden.</p>\n\n<p>Meine Anfrage schlie&szlig;t explizit auch s&auml;mtliche weiteren Angebote und Unternehmen ein, f&uuml;r die Sie Verantwortlicher im Sinne des Art. 4 Nr. 7 DSGVO sind.</p>\n\n<p>Nach Art. 12 Abs. 3 DSGVO haben Sie mich unverz&uuml;glich, sp&auml;testens aber innerhalb eines Monats nach Eingang des Antrags, &uuml;ber die vorgenommenen L&ouml;schungen zu informieren.</p>\n\n<p>Sollten Sie meinem Antrag nicht innerhalb der genannten Frist nachkommen, behalte ich mir vor rechtliche Schritte gegen Sie einzuleiten und Beschwerde bei der zust&auml;ndigen Datenschutzaufsichtsbeh&ouml;rde einzureichen.</p>\n\n<p>Schon im Voraus vielen Dank f&uuml;r Ihre M&uuml;he.</p>\n\n<p>Mit freundlichen Gr&uuml;&szlig;en</p>\n\n<p><br>\n&nbsp;</p>",
    inputs: [
      {
        input_type: "end_node",
        text: "",
      },
    ],
    newNode: false,
    startNode: false,
    endNode: true,
    extraData: null,
    id: "5",
    createdAt: "2020-06-17T15:45:29.204008+00:00",
  },
  {
    name: "Kundendaten Löschung",
    slug: "kundendaten-loschung",
    path: "",
    question:
      "<p>Damit Du Deinen Anspruch auch durchsetzen kannst, muss das Unternehmen Dich identifizieren k&ouml;nnen.</p>\n\n<p>Hierzu reicht Dein Name sowie die E-Mail, &uuml;ber die Du mit dem Unternehmen kommuniziert hast, oder etwas anderes, das Dir eindeutig zuordenbar ist, aus.</p>\n\n<p>Bitte gib nicht mehr Daten an, als wirklich notwendig sind.&nbsp;</p>",
    inputs: [
      {
        input_type: "free_text",
        text: "Kundenummer",
        validation: "short_text",
        destination: "5",
      },
    ],
    newNode: false,
    startNode: false,
    endNode: false,
    extraData: "",
    id: "6",
    createdAt: "2020-06-17T15:43:03.510310+00:00",
  },
  {
    name: "werbewiderruf",
    slug: "werbewiderruf",
    path: null,
    question: "",
    inputs: [{}],
    newNode: true,
    startNode: false,
    endNode: false,
    extraData: null,
    id: "7",
    createdAt: "2020-06-17T15:39:03.900226+00:00",
  },
  {
    name: "Einwilligungswiderruf",
    slug: "einwilligungswiderruf",
    path: null,
    question: "",
    inputs: [{}],
    newNode: true,
    startNode: false,
    endNode: false,
    extraData: null,
    id: "8",
    createdAt: "2020-06-12T12:29:30.732777+00:00",
  },
];
