query ALL_TREES {
  allDecisionTrees {
    edges {
      node {
        id
        name
        tags
        createdAt
      }
    }
  }
}

mutation CREATE_TREE($input: CreateDecisionTreeMutationInput!) {
  createTree(input: $input) {
    tree {
      id
      name
      extraData
      tags
    }
  }
}
